---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: artalk-secrets
  namespace: blog
spec:
  encryptedData:
    admin-password: AgB/lkIXV6pU7FqXL9pnJOKEorQtQnrtqOdIxBu4DIzd8eMhU5z8ZSu5yE9UJA56v06zqFh2vLtWLMK6T49umykx8I1DXEt5QySyEO8U+Bfk0WEaF+UhMKEBIzRIiuRhqMHQ9Y+noRaQe0QRzOZmGWngQXbBYvoGKvtERs8rePIF/svUFhwA/StZQ075us/ncjgJYTTJsOheCCDtlS8c6k3tgoI6tFiQwl15aHgSb2gB+aRVzZ/CmDRuO9as50VS0i3hRzv/i44/5jtwXYJ4inVTYwscvZRSEP0BF4qHm5xm6SCi7i144NvaJl5VJhsBZ+XKFaxC+sD3aDtmkfbbeGmBr+xmFKHvEtY0c4KrRsw9h1oEqWPRKw5Ttew7901r1Z7LEV70VpCa4GRbPDanAIEhRn0obsnxlWsXV48ZEK/F7QzvXtV+WfaQ06qb8zGe2rdmn4OWsq6za/f/R/r9FUJgRPqbSqFJlCbdBd/78HQxWssDTtq9nGeYnhs1sRfACp0im8aQPnKHwcs2tt1XwDAn+2HKCj4AzEzHOpY543cGoO7JYB8xEsk7EA/rJoir7vaWxnnrLsfXqQ4fjW0L6P1a5Ni4kxDxfIJMCdD2XKgBIcIo9H4P7nN58D6MniDpQTMwpprLx863+Ye2WwsZWfo8WwIpcthtPNdfPZmok8tXqQQcaipB6W9hJPc4/rdNu3wj/e5TeevZFgI9HC1nwB0okkGLNA==
    app-key: AgCcikQbtSdx31jdza4rpDmi4QMobM+2sVCApy8u0n6JU9gNtPgucag3Hct9V2LUkzcBgICy6FMGADmhDa2w2S1dV6Vnlp+F3AjSFYzNDYTIgO7DliCxuI3ZFD1mPR/888f+bTWCI5FlKJ1kf7ths+H8oo4Fx7W9AGVCyjeSDE9BJNEynVBxcVF8dofKsaQSkYl6MRNXxlveUZ5u/LmhCWmrNA5bSCJTggErx0ri4yFnZ7myACWjh+mVWLH/YjiGxlLmoQ6/NPkOuPvlVxIH2L1e+LFAnLA23FyZRIuLISg2txqBcu1SIRFeCSlnIyXCPRlY0705vJu3/jB25fazxuaGBI3BKyZSB+n/DfIvqHxZoeQIvQMnE51yW6OdKvGZVVkNqtYVMNxmnaYBFF2wWUpZygU0nyinHplJ+tUF35ewrTGANcevd0v0tt/5OJJi6UFvUzDrhvPRCdM0PYc4QlkTEykhHvAhYvxBCpRmF4dU3Fwbv9uuMjiZrB7xixajgJlbXO0JAy16bqRiEoo+Purc2LEg0dTOoVTXcKXw9M1/KQBQNtTMSVeQrS4ycY4D9mWs0KbunnWqaIueKzU3Vm9EyA0QTeult2k03tkuONGqhheKiGCBl8uobOOtuwcht8szHx5ihVScyoktLXG8UNNarbfD3U3jpgavYOimCDOKV8BQmqDluqAZftKJylpDNDkOmI13Xlg+zalfGnDv4zIvXzH03DolX8wIUnuTpMNzqot2Xf0ijIDA1qGf0rrEzoi08jYgftLaQEQcEdq+M76S
  template:
    metadata:
      name: artalk-secrets
      namespace: blog
