---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: remark42-secrets
  namespace: blog
spec:
  encryptedData:
    admin-passwd: AgChak7IBIzMm6oFAsOL5ITKv/8iWWiCdE05ZSpSCV80aQ5F+8LpwTuvzecBFV4RGvv3/tupMHOgIdQCpFwFZ7bCeH1prgVLOv7vL61rICtDgoCtbbK1Bc2xJpohu421UHiYnrVAn7Gd5gTgiYMCPTAZ5NXp5iVeonrGLde0vbRafwEXAqMxHXUfkGzssvQQMBJw9TlKKBdNVlYzWN0hlfx4BlTevKYlV385haCdEBJ1wma9YXqbgw74buC+eA+HRpa8PDUt1szlRWNzJGYqTk+A8cZBxIE6aDpUsbU4FLsxKegkJoGC1nKcMs7ss1UDQUlfzd0oO9wesSZF7NlYvMwTOjawp69JxGlj3uvYLXxQ7XTnuc35TbMqAhW6BYPvf3IitiTXWGLNHPLUbupMcaWZX8fM8b6xHpaEMBmTHlwi1hDKWLJBSdFbJCedZTe4opAE1zQgO1fMUd0ZpR39+8MTsrsLY2DwiO53Ncz2N/3vSdpveBVBtfqC2ymfXEW9liXg6TIVNZZsq0brWeYrGPsh9A3usL/0kIr8KVurBECE73o/Xg+ISC/VDMv/cFNen13OH/elFkiCWGN0Essfz5wucgOE94gLxoItnCSFq1qx3PZdmaKUrtuhAioc2nBIqz7yW4vGyjV+uugBprWmvhiXdTWIJyMYHSzT9SmokoqC9w5syknWeUPcydiGGotAkZOZavZyx/bqP1BBZYraAI6ODVic3R+ymZU=
    secret: AgBgGcrLMKaClMVbQO4q1hST++z1UWVPnyLbz/yEWIe5TukwF4/LK5sVCbH0jXJBJF0qGXEfMPozngk3hzy8K2/oIU1Xiej1JFJOXwMbxncsglvf5Xstr2OtBfTuvk85xgxQpBoBKwz/hQ8DZUUUMTwNiHyLRlUjjqb5BX/fk8LyGZfJE/5UC6M4M/kL+tuO+RwunwPbU7mi78mE/jzRaz9KTtmocILXd/23pe/+4SN9qqQRq1FWz1kllqgGNxAfjLvjOJNMH7k91ibYlo17piZXt0Tr6jgX3xwwJkaFVf9byoUPlnxe5D8R3cSKdiwPmkM3j82yDBWuW6saen4tMmJJ/YLT0SQX2PJscvuCEAeuzM7WU0bLsgZQSYXqIaSt6hEEHO9NITAGUponIz/jbxRR6wSVyFFBpTMMdfnGfofXZXRKmabojf1S+sbzCbMaGWC/vk1tI1AY/U9Uv3Bfsb14TFSd8lFI5emJz7160xApVY3M05nzrTcrNqzM64DYurGgJcdD6kBMuEZScd/8VOMlDDbenigXj3JGPdKXux1BUQy4GR9OdOdyfOmX8hO9IT7wGCGP/Zp2/nI6mrhtITbqArcivCiKlybsIU5xG0CPuqKFYZ1cVhAqu18pEkf9AUEHLLD9QslaK3yRioioq3HtZuooaFmidhLaJ+wHjMIjQ0s8MdX0sx4ebofITzuOniLyH3jEp110GJXHEzLPkTh+GTrNydgbDx+rPcGly7whw+gx5fIvp6X+ix644w==
  template:
    metadata:
      name: remark42-secrets
      namespace: blog
    type: Opaque
